# name: base
name: ai
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - _anaconda_depends=2020.07=py38_0
  - _ipyw_jlab_nb_ext_conf=0.1.0=py38_0
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - alabaster=0.7.12=pyhd3eb1b0_0
  - anaconda=custom=py38_1
  - anaconda-client=1.9.0=py38h06a4308_0
  - anaconda-navigator=2.0.3=py38_0
  - anaconda-project=0.10.2=pyhd3eb1b0_0
  - anyio=3.5.0=py38h06a4308_0
  - appdirs=1.4.4=pyhd3eb1b0_0
  - argh=0.26.2=py38_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py38h7f8727e_0
  - async_generator=1.10=pyhd3eb1b0_0
  - atomicwrites=1.4.0=py_0
  - attrs=21.4.0=pyhd3eb1b0_0
  - babel=2.9.1=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - backports=1.1=pyhd3eb1b0_0
  - backports.functools_lru_cache=1.6.4=pyhd3eb1b0_0
  - backports.shutil_get_terminal_size=1.0.0=pyhd3eb1b0_3
  - backports.tempfile=1.0=pyhd3eb1b0_1
  - backports.weakref=1.0.post1=py_1
  - beautifulsoup4=4.10.0=pyh06a4308_0
  - binaryornot=0.4.4=pyhd3eb1b0_1
  - bkcharts=0.2=py38_0
  - blas=1.0=mkl
  - bleach=4.1.0=pyhd3eb1b0_0
  - blosc=1.21.0=h8c45485_0
  - bokeh=2.4.2=py38h06a4308_0
  - boto=2.49.0=py38_0
  - brotli=1.0.9=he6710b0_2
  - brotlipy=0.7.0=py38h27cfd23_1003
  - brunsli=0.1=h2531618_0
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.18.1=h7f8727e_0
  - ca-certificates=2022.2.1=h06a4308_0
  - cairo=1.16.0=hf32fb01_1
  - certifi=2021.10.8=py38h06a4308_2
  - cffi=1.15.0=py38hd667e15_1
  - cfitsio=3.470=hf0d0db6_6
  - chardet=4.0.0=py38h06a4308_1003
  - charls=2.2.0=h2531618_0
  - click=8.0.4=py38h06a4308_0
  - cloudpickle=2.0.0=pyhd3eb1b0_0
  - clyent=1.2.2=py38_1
  - colorama=0.4.4=pyhd3eb1b0_0
  - conda=4.11.0=py38h06a4308_0
  - conda-build=3.21.4=py38h06a4308_0
  - conda-content-trust=0.1.1=pyhd3eb1b0_0
  - conda-env=2.6.0=1
  - conda-pack=0.6.0=pyhd3eb1b0_0
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - conda-repo-cli=1.0.4=pyhd3eb1b0_0
  - conda-token=0.3.0=pyhd3eb1b0_0
  - conda-verify=3.4.2=py_1
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - curl=7.80.0=h7f8727e_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - dask-core=2021.10.0=pyhd3eb1b0_0
  - dataclasses=0.8=pyh6d0b6a4_7
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - diff-match-patch=20200713=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - et_xmlfile=1.1.0=py38h06a4308_0
  - expat=2.4.4=h295c915_0
  - fastcache=1.1.0=py38h7b6447c_0
  - ffmpeg=4.2.2=h20bf706_0
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - fribidi=1.0.10=h7b6447c_0
  - future=0.18.2=py38_1
  - get_terminal_size=1.0.0=haa9412d_0
  - giflib=5.2.1=h7b6447c_0
  - glib=2.69.1=h4ff587b_1
  - glob2=0.7=pyhd3eb1b0_0
  - gmp=6.2.1=h2531618_2
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - graphite2=1.3.14=h23475e2_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - harfbuzz=2.8.1=h6f93f22_0
  - hdf5=1.10.4=hb1b8bf9_0
  - heapdict=1.0.1=pyhd3eb1b0_0
  - html5lib=1.1=pyhd3eb1b0_0
  - icu=58.2=he6710b0_3
  - idna=3.3=pyhd3eb1b0_0
  - imagesize=1.3.0=pyhd3eb1b0_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - inflection=0.5.1=py38h06a4308_0
  - iniconfig=1.1.1=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - intervaltree=3.1.0=pyhd3eb1b0_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jbig=2.1=hdba287a_0
  - jdcal=1.4.1=pyhd3eb1b0_0
  - jeepney=0.7.1=pyhd3eb1b0_0
  - jinja2-time=0.2.0=pyhd3eb1b0_2
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - json5=0.9.6=pyhd3eb1b0_0
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.1.2=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38h06a4308_0
  - jupyter_server=1.13.5=pyhd3eb1b0_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.10.3=pyhd3eb1b0_1
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - jxrlib=1.1=h7b6447c_2
  - kiwisolver=1.3.2=py38h295c915_0
  - krb5=1.19.2=hac12032_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - lerc=2.2.1=h2531618_0
  - libaec=1.0.4=he6710b0_1
  - libarchive=3.4.2=h62408e4_0
  - libcurl=7.80.0=h0b77cf5_0
  - libdeflate=1.7=h27cfd23_5
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - liblief=0.10.1=he6710b0_0
  - libllvm10=10.0.1=hbcb73fb_5
  - libllvm11=11.1.0=h3826bc1_0
  - libllvm9=9.0.1=h4a3c616_1
  - libnghttp2=1.46.0=hce63b2e_0
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libspatialindex=1.9.3=h2531618_0
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.1.0=h2733197_1
  - libtool=2.4.6=h295c915_1008
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=1.0.3=h7f8727e_2
  - libuv=1.40.0=h7b6447c_0
  - libvpx=1.7.0=h439df22_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - libxslt=1.1.34=hc22bd24_0
  - libzopfli=1.0.3=he6710b0_0
  - locket=0.2.1=py38h06a4308_1
  - lxml=4.8.0=py38h1f438cf_0
  - lz4-c=1.9.3=h295c915_1
  - lzo=2.10=h7b6447c_2
  - matplotlib=3.5.1=py38h06a4308_0
  - matplotlib-base=3.5.1=py38ha18d171_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mock=4.0.3=pyhd3eb1b0_0
  - more-itertools=8.12.0=pyhd3eb1b0_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py38h06a4308_0
  - msgpack-python=1.0.2=py38hff7bd54_1
  - multipledispatch=0.6.0=py38_0
  - munkres=1.1.4=py_0
  - mypy_extensions=0.4.3=py38h06a4308_1
  - navigator-updater=0.2.1=py38_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - nettle=3.7.3=hbbd107a_1
  - ninja=1.10.2=py38hd09550d_3
  - nltk=3.7=pyhd3eb1b0_0
  - nose=1.3.7=pyhd3eb1b0_1008
  - notebook=6.4.8=py38h06a4308_0
  - numexpr=2.8.1=py38h6abb31d_0
  - numpy-base=1.20.3=py38h74d4b33_0
  - numpydoc=1.2=pyhd3eb1b0_0
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.4.0=h3ad879b_0
  - openpyxl=3.0.9=pyhd3eb1b0_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandas=1.4.1=py38h295c915_0
  - pandoc=2.12=h06a4308_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.45.3=hd140c19_0
  - partd=1.2.0=pyhd3eb1b0_0
  - patchelf=0.13=h295c915_0
  - path.py=12.5.0=hd3eb1b0_0
  - pathtools=0.1.2=pyhd3eb1b0_1
  - patsy=0.5.2=py38h06a4308_1
  - pcre=8.45=h295c915_0
  - pep8=1.7.1=py38_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pixman=0.40.0=h7f8727e_1
  - pkginfo=1.8.2=pyhd3eb1b0_0
  - pluggy=1.0.0=py38h06a4308_0
  - ply=3.11=py38_0
  - poyo=0.5.0=pyhd3eb1b0_0
  - prometheus_client=0.13.1=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - py=1.11.0=pyhd3eb1b0_0
  - py-lief=0.10.1=py38h403a769_0
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.21=pyhd3eb1b0_0
  - pycurl=7.44.1=py38h8f2d780_1
  - pydocstyle=6.1.1=pyhd3eb1b0_0
  - pygments=2.11.2=pyhd3eb1b0_0
  - pylint=2.12.2=py38h06a4308_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pysocks=1.7.1=py38h06a4308_0
  - pytables=3.6.1=py38h9fd0a39_0
  - python=3.8.8=hdb3f193_5
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python-jsonrpc-server=0.4.0=py_0
  - python-language-server=0.36.2=pyhd3eb1b0_0
  - python-libarchive-c=2.9=pyhd3eb1b0_1
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyxdg=0.27=pyhd3eb1b0_0
  - pyyaml=6.0=py38h7f8727e_1
  - pyzmq=22.3.0=py38h295c915_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.2.2=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - requests=2.27.1=pyhd3eb1b0_0
  - ripgrep=12.1.1=0
  - rtree=0.9.7=py38h06a4308_1
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - scikit-learn=1.0.2=py38h51133e4_1
  - seaborn=0.11.2=pyhd3eb1b0_0
  - secretstorage=3.3.1=py38h06a4308_0
  - send2trash=1.8.0=pyhd3eb1b0_1
  - simplegeneric=0.8.1=py38_2
  - singledispatch=3.7.0=pyhd3eb1b0_1001
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.8=he6710b0_0
  - sniffio=1.2.0=py38h06a4308_1
  - snowballstemmer=2.2.0=pyhd3eb1b0_0
  - sortedcollections=2.1.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - soupsieve=2.3.1=pyhd3eb1b0_0
  - sphinx=4.4.0=pyhd3eb1b0_0
  - sphinxcontrib=1.0=py38_1
  - sphinxcontrib-applehelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-devhelp=1.0.2=pyhd3eb1b0_0
  - sphinxcontrib-htmlhelp=2.0.0=pyhd3eb1b0_0
  - sphinxcontrib-jsmath=1.0.1=pyhd3eb1b0_0
  - sphinxcontrib-qthelp=1.0.3=pyhd3eb1b0_0
  - sphinxcontrib-serializinghtml=1.1.5=pyhd3eb1b0_0
  - sphinxcontrib-websupport=1.2.4=py_0
  - sqlite=3.37.2=hc218d9a_0
  - tbb=2021.5.0=hd09550d_0
  - tblib=1.7.0=pyhd3eb1b0_0
  - text-unidecode=1.3=pyhd3eb1b0_0
  - three-merge=0.1.1=pyhd3eb1b0_0
  - tinycss=0.4=pyhd3eb1b0_1002
  - tk=8.6.11=h1ccaba5_0
  - toml=0.10.2=pyhd3eb1b0_0
  - toolz=0.11.2=pyhd3eb1b0_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - unicodecsv=0.14.1=py38_0
  - unixodbc=2.3.9=h7b6447c_0
  - urllib3=1.26.8=pyhd3eb1b0_0
  - watchdog=2.1.6=py38h06a4308_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - werkzeug=2.0.3=pyhd3eb1b0_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - whichcraft=0.6.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.2=py38h06a4308_0
  - wrapt=1.13.3=py38h7f8727e_2
  - wurlitzer=3.0.2=py38h06a4308_0
  - x264=1!157.20191217=h7b6447c_0
  - xlrd=2.0.1=pyhd3eb1b0_0
  - xlwt=1.3.0=py38_0
  - xmltodict=0.12.0=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zfp=0.5.5=h295c915_6
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - zope=1.0=py38_1
  - zope.event=4.5.0=py38_0
  - zope.interface=5.4.0=py38h7f8727e_0
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - aggdraw==1.3.14
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - arrow==1.2.2
    - asn1crypto==1.5.0
    - astroid==2.10.0
    - astropy==5.0.1
    - asttokens==2.0.5
    - astunparse==1.6.3
    - async-timeout==4.0.2
    - autopep8==1.6.0
    - bitarray==2.4.0
    - black==22.1.0
    - bottleneck==1.3.4
    - cachetools==5.0.0
    - charset-normalizer==2.0.12
    - configparser==5.2.0
    - contextlib2==21.6.0
    - cookiecutter==1.7.3
    - coremltools==5.2.0
    - cryptography==36.0.1
    - cython==0.29.28
    - cytoolz==0.11.2
    - dask==2022.2.1
    - decorator==4.4.2
    - deprecation==2.1.0
    - distributed==2022.2.1
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - docutils==0.18.1
    - executing==0.8.3
    - filelock==3.6.0
    - flake8==4.0.1
    - flask==2.0.3
    - flatbuffers==2.0
    - fonttools==4.29.1
    - frozenlist==1.3.0
    - fsspec==2021.10.1
    - fvcore==0.1.5.post20220305
    - gast==0.5.3
    - gevent==21.12.0
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.6.0
    - google-auth-oauthlib==0.5.0
    - google-pasta==0.2.0
    - greenlet==1.1.2
    - grpcio==1.44.0
    - gviz-api==1.10.0
    - h5py==3.6.0
    - imagecodecs==2022.2.22
    - imageio==2.16.1
    - imageio-ffmpeg==0.4.5
    - importlib-metadata==4.11.2
    - importlib-resources==5.4.0
    - iopath==0.1.9
    - ipykernel==6.9.1
    - ipython==8.1.1
    - isort==5.10.1
    - itsdangerous==2.1.1
    - jedi==0.18.1
    - jellyfish==0.9.0
    - jinja2==3.0.3
    - jsonschema==4.4.0
    - jupyter-console==6.4.3
    - jupyter-core==4.9.2
    - jupyter-packaging==0.11.1
    - jupyterlab==3.3.1
    - jupyterlab-widgets==1.0.2
    - keras==2.8.0
    - keras-preprocessing==1.1.2
    - keyring==23.5.0
    - lazy-object-proxy==1.7.1
    - libarchive-c==4.0
    - libclang==13.0.0
    - llvmlite==0.38.0
    - markdown==3.3.6
    - markupsafe==2.1.0
    - matplotlib-inline==0.1.3
    - mccabe==0.7.0
    - mistune==2.0.2
    - moviepy==1.0.3
    - msgpack==1.0.3
    - multidict==6.0.2
    - nbclassic==0.3.6
    - nbclient==0.5.12
    - nbconvert==6.4.2
    - nest-asyncio==1.5.4
    - networkx==2.7.1
    - notebook-shim==0.1.0
    - numba==0.55.1
    - numpy==1.22.3
    - oauthlib==3.2.0
    - opencv-python==4.5.5.64
    - opt-einsum==3.3.0
    - parso==0.8.3
    - path==16.4.0
    - pathlib2==2.3.7.post1
    - pathspec==0.9.0
    - pillow==9.0.1
    - pip==22.0.4
    - platformdirs==2.5.1
    - portalocker==2.4.0
    - proglog==0.1.9
    - promise==2.3
    - prompt-toolkit==3.0.28
    - protobuf==3.19.4
    - psd-tools==1.9.18
    - psutil==5.9.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.8.0
    - pydeprecate==0.3.2
    - pydevd==2.8.0
    - pyerfa==2.0.0.1
    - pyflakes==2.4.0
    - pyls-black==0.4.7
    - pyls-spyder==0.4.0
    - pymaxflow==1.2.13
    - pyodbc==4.0.32
    - pyparsing==3.0.7
    - pyqt5==5.15.6
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.9.1
    - pyqtwebengine==5.15.5
    - pyqtwebengine-qt5==5.15.2
    - pyrsistent==0.18.1
    - pytest==7.0.1
    - python-lsp-black==1.1.0
    - python-lsp-jsonrpc==1.0.0
    - python-lsp-server==1.3.3
    - python-slugify==6.1.1
    - pytorch-lightning==1.5.10
    - pywavelets==1.2.0
    - qdarkstyle==3.0.3
    - qstylizer==0.2.1
    - qtawesome==1.1.1
    - qtpy==2.0.1
    - regex==2022.3.2
    - requests-oauthlib==1.3.1
    - rope==0.23.0
    - rsa==4.8
    - scikit-image==0.19.2
    - scipy==1.8.0
    - sentry-sdk==1.5.7
    - setproctitle==1.2.2
    - setuptools==59.5.0
    - shortuuid==1.0.8
    - sip==6.5.1
    - smmap==5.0.0
    - spyder==5.2.2
    - spyder-kernels==2.2.1
    - sqlalchemy==1.4.32
    - stack-data==0.2.0
    - statsmodels==0.13.2
    - subprocess32==3.5.4
    - sympy==1.10
    - tables==3.7.0
    - tabulate==0.8.9
    - tensorboard==2.8.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-profile==2.5.0
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5
    - tensorflow==2.8.0
    - tensorflow-estimator==2.8.0
    - tensorflow-io-gcs-filesystem==0.24.0
    - termcolor==1.1.0
    - terminado==0.13.3
    - testpath==0.6.0
    - textdistance==4.2.2
    - tf-estimator-nightly==2.8.0.dev2021122109
    - threadpoolctl==3.1.0
    - tifffile==2022.2.9
    - tinycss2==1.1.1
    - tomli==2.0.1
    - tomlkit==0.10.0
    - torch==1.10.2
    - torchaudio==0.10.2
    - torchcontrib==0.0.2
    - torchinfo==1.6.3
    - torchmetrics==0.7.2
    - torchvision==0.11.3
    - tqdm==4.63.0
    - typed-ast==1.5.2
    - typing-extensions==4.1.1
    - ujson==5.1.0
    - unidecode==1.3.3
    - wandb==0.12.11
    - websocket-client==1.3.1
    - xlsxwriter==3.0.3
    - yacs==0.1.8
    - yapf==0.32.0
    - yarl==1.7.2
    - yaspin==2.1.0
    - zict==2.1.0
#Commented out the prefix
# prefix: /home/grg/anaconda3
